
- name: Couchbase Installation
  hosts: all
  user: johndoyle
   
  tasks:

  - name: clean up prior couchbase lib
    shell: rm -rf ~/Library/Application Support/Couchbase

  - name: clean up prior memcache lib
    shell: rm -rf ~/Library/Application Support/Membase

  - name: clean up prior couchbase app
    shell: rm -rf /Applications/Couchbase\ Server.app

  - name: download Couchbase package
    get_url: url=http://packages.couchbase.com/releases/2.2.0/couchbase-server-community_2.2.0_x86_64.zip dest=~/.

  - name: Unzip the Couchbase package
    shell: unzip ~/couchbase-server-community_2.2.0_x86_64.zip -d ~/

  - name: Move to Applications
    shell: mv ~/Couchbase\ Server.app/ /Applications
 
  - name: clean up read me
    shell: rm ~/README.txt

  - name: clean up zip file
    shell: rm ~/couchbase-server-community_2.2.0_x86_64.zip

- name: Initialize the cluster and add the nodes to the cluster
  hosts: couchbase-main
  user: root 

  tasks:
  - name: Configure main node
    shell: /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/couchbase-cli cluster-init -c 127.0.0.1:8091  --cluster-init-username=${admin_user} --cluster-init-password=${admin_password} --cluster-init-port=8091 --cluster-init-ramsize=${cluster_ram_quota} 

  - name: Rebalance the cluster
    shell: /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/couchbase-cli rebalance -c 127.0.0.1:8091 -u ${admin_user} -p ${admin_password}      
  
  - name: create bucket ${bucket_name} with ${num_replicas} replicas
    shell: /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=${bucket_name} --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=${bucket_ram_quota}  --bucket-replica=${num_replicas} -u ${admin_user} -p ${admin_password}

